apiVersion: v1
kind: Service
metadata:
  name: svc-grafana
  namespace: grafana
spec:
  ports:
    - port: 10009
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer