apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-binding
  namespace: azure
subjects:
- kind: ServiceAccount
  name: external-secrets
  namespace: external-secrets  # 👈 Adjust this based on where your external-secrets controller runs!
roleRef:
  kind: Role
  name: external-secrets-reader
  apiGroup: rbac.authorization.k8s.io