apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nzbget
  namespace: nzbget
spec:
  storageClassName: sc-smb-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi