apiVersion: v1
kind: Service
metadata:
  name: svc-nzbget
  namespace: nzbget
  labels:
    app: nzbget
  annotations:
spec:
  type: LoadBalancer
  ports:
  - port: 10003
    targetPort: 6789s
  selector:
    app: nzbget