apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox
  namespace: blackbox
  labels:
    app: blackbox
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: blackbox
          image: "quay.io/prometheus/blackbox-exporter:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /config
              name: config
          ports:
            - containerPort: 9115
              protocol: TCP
      volumes:
      - name: config
        hostPath:
          path: /etc/configs/blackbox
