apiVersion: v1
kind: Service
metadata:
  name: svc-blackbox
  namespace: blackbox
  labels:
    app: blackbox
  annotations:
spec:
  type: LoadBalancer
  ports:
  - port: 10011
    targetPort: 9115
  selector:
    app: blackbox