apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: smb
  namespace: azure
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: smb-secrets
    creationPolicy: Owner

  data:
  - secretKey: smbuser
    remoteRef:
      key: smbuser

  - secretKey: smbpassword
    remoteRef:
      key: smbpassword