apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nfs
provisioner: csi.san.synology.com
parameters:
  dsm: '192.168.178.2'
  location: "/volume1"
  mountPermissions: '0755'
mountOptions:
  - nfsvers=4.1
reclaimPolicy: Retain
allowVolumeExpansion: true