apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-letsencrypt
  namespace: nginx-proxymanager
spec:
  storageClassName: sc-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi