apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mealie
  namespace: mealie
spec:
  storageClassName: sc-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi