apiVersion: v1
kind: Service
metadata:
  name: svc-mealie
  namespace: mealie
  labels:
    app: mealie
  annotations:
spec:
  type: LoadBalancer
  ports:
  - port: 10004
    targetPort: 9000
  selector:
    app: mealie