apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: adguard
  labels:
    app: adguard
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
        - name: adguard
          image: adguard/adguardhome:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /opt/adguardhome/work
              name: adguard
          ports:
            - containerPort: 53 #dns
              name: dns
              protocol: UDP
            - containerPort: 3000 #initial setup
              name: http-initial
            - containerPort: 80 #web gui
              name: http
              protocol: TCP
      volumes:
      - name: config
        hostPath:
          path: /etc/configs/adguard
      - name: adguard
        persistentVolumeClaim:
          claimName: pvc-adguard
