apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-adguard
  namespace: adguard
spec:
  storageClassName: sc-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi