apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim
  namespace: valheim
  labels:
    app: valheim
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: valheim
  template:
    metadata:
      labels:
        app: valheim
    spec:
      containers:
        - name: valheim
          image: "docker.io/lloesche/valheim-server:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
          env:
            - name: TZ
              value: Etc/UTC
          ports:
            - containerPort: 2456
              protocol: UDP
            - containerPort: 2457
              protocol: UDP
      volumes:
      - name: config
        hostPath:
          path: /etc/configs/valheim
      - name: data
        hostPath:
          path: /etc/data/valheim
