apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-valheim
  namespace: azure
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: es-valheim-secrets
    creationPolicy: Owner

  data:
  - secretKey: SERVER_PASS
    remoteRef:
      key: valheimpassword