apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-valheim
  namespace: valheim
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secret-store
  data:
  - secretKey: SERVER_PASS
    remoteRef:
      key: valheimpassword