apiVersion: v1
kind: Service
metadata:
  name: svc-valheim
  namespace: valheim
  labels:
    app: valheim
  annotations:
spec:
  type: LoadBalancer
  ports:
  - port: 10006
    targetPort: 2456
    protocol: UDP
    name: private-port
  - port: 10007
    targetPort: 2457
    protocol: UDP
    name: public-port
  selector:
    app: valheim