apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-guide
  namespace: gardenize
  labels:
    app: gardenize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gardenize
  template:
    metadata:
      labels:
        app: gardenize
    spec:
      containers:
        - name: gardenize
          image: docker.io/gardenize1337/garden-guide:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi