apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: es-smb
  namespace: azure
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store

  target:
    name: smb-secrets
    creationPolicy: Owner

  data:
  - secretKey: username
    remoteRef:
      key: smbuser

  - secretKey: password
    remoteRef:
      key: smbpassword