apiVersion: v1
kind: Service
metadata:
  name: svc-prometheus
  namespace: prometheus
  labels:
    app: prometheus
  annotations:
spec:
  type: LoadBalancer
  ports:
  - port: 10010
    targetPort: 9090
  selector:
    app: prometheus