apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app: minecraft
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: "docker.io/itzg/minecraft-server:1.21.4"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
          envFrom:
            - configMapRef:
                name: cm-minecraft
          ports:
            - containerPort: 25565            
              protocol: TCP
      volumes:
      - name: config
        hostPath:
          path: /etc/configs/minecraft
      - name: data
        hostPath:
          path: /etc/data/minecraft
 