apiVersion: v1
kind: Service
metadata:
  name: svc-minecraft
  namespace: minecraft
  labels:
    app: minecraft
  annotations:
spec:
  type: LoadBalancer
  ports:
  - port: 10008
    targetPort: 25565
  selector:
    app: minecraft