apiVersion: v1
kind: Service
metadata:
  name: svc-plex
  namespace: plex
  labels:
    app: plex
  annotations:
spec:
  type: LoadBalancer
  ports:
  - port: 10001
    targetPort: 32400
  selector:
    app: plex